#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

pushd cf-release
  git submodule update --init --recursive
popd

rm -rf diego-release/cf-release
cp -R cf-release diego-release/

rm -rf "diego-release/${DEPLOYMENTS_DIR}"
cp -R "${DEPLOYMENTS_DIR}" diego-release/

pushd diego-release
  ./scripts/ci/create_drone_yml scripts/ci/create_cf_release.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
