image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - INFRASTRUCTURE={{INFRASTRUCTURE}}
  - DEPLOYMENTS_DIR={{DEPLOYMENTS_DIR}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}
  - STUBS_DIR={{STUBS_DIR}}
  - DATADOG_API_KEY={{DATADOG_API_KEY}}

script:
  - ./scripts/ci/create_cf_release_inner

cache:
  - /tmp/cache
  - cf-release/.blobs
  - output
  - .blobs
